# Project information
site_name: SAFE Documentation
site_description: Documentation for SAFE
site_author: SAFE Stack
site_url: http://safe-stack.github.io/docs/

# Repository
repo_name: SAFE-Stack/docs
repo_url: https://github.com/SAFE-Stack/docs
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'orange'
    accent: 'blue'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/SAFE-Stack'
    - type: 'twitter'
      link: 'https://twitter.com/safe_stack'
    - type: 'globe'
      link: https://safe-stack.github.io/

pages:
- Home: 'index.md'
- Introduction: 'intro.md'
- SAFE Stack Overview : 'overview.md'
- Quick Start: 'quickstart.md'
- Learn about SAFE:
  - 'Client Server communication' : 'client-server.md'
  - 'Learning Resources': 'learning.md'
- Support: 'support.md'
- Testimonials: 'testimonials.md'
