# Project information
site_name: SAFE Documentation
site_description: Documentation for SAFE
site_author: SAFE Stack
site_url: http://safe-stack.github.io/docs/

# Repository
repo_name: SAFE-Stack/docs
repo_url: https://github.com/SAFE-Stack/docs
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'orange'
    accent: 'blue'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/SAFE-Stack'
    - type: 'twitter'
      link: 'https://twitter.com/safe_stack'
    - type: 'globe'
      link: https://safe-stack.github.io/

pages:
- Home: 'index.md'
- Introduction: 'intro.md'
- Getting Started:
  - 'Quick Start': 'quickstart.md'
  - 'The SAFE template': 'safe-template.md'
- Learn about SAFE:
  - 'SAFE Stack Overview' : 'overview.md'
  - Components of SAFE:
    - 'Learn about Saturn' : 'safe-saturn.md'
    - 'Learn about Azure' : 'safe-azure.md'
    - 'Learn about Fable' : 'safe-fable.md'
    - 'Learn about Elmish' : 'safe-elmish.md'
    - 'Choosing your web server' : 'safe-server.md'
  - Features of SAFE:
    - 'Client Server communication' : 'feature-client-server.md'
    - 'Server Side Rendering' : 'feature-ssr.md'
    - 'Hot Module Replacement' : 'feature-hmr.md'
  - 'Learning Resources': 'learning.md'
- Support: 'support.md'
- Testimonials: 'testimonials.md'
